apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-07-10T22:07:11Z"
  generation: 1
  labels:
    app: prometheus
  name: prometheus
  namespace: default
  resourceVersion: "20810"
  uid: f92a46aa-c726-4061-81bc-6f97fcf9c67a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa
      containers:
      - image: prom/prometheus
        imagePullPolicy: Always
        name: prometheus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: prometheus
          mountPath: /etc/prometheus/
      - image: prom/alertmanager
        imagePullPolicy: IfNotPresent
        name: alertmanager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: alertmanager
            mountPath: /etc/alertmanager/
      volumes: 
      - name: prometheus
        configMap:
          defaultMode: 420
          name: prometheus
      - name: alertmanager
        configMap:  
          defaultMode: 420
          name: alertmanager
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-10T22:07:21Z"
    lastUpdateTime: "2022-07-10T22:07:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-07-10T22:07:11Z"
    lastUpdateTime: "2022-07-10T22:07:21Z"
    message: ReplicaSet "prometheus-657bd7b667" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
